version: '3.4'

services:
  medcattrainer:
    container_name: medcattrainer
    hostname: medcat
    restart: always
    image: cogstacksystems/medcat-trainer:v2.3.7
    volumes:
      - ./configs:/home/configs
      - api-media:/home/api/media
      - api-static:/home/api/static
      - api-db:/home/api/db
    expose:
      - "8000"
    env_file:
      - ./envs/env-prod
    environment:
      - MCT_VERSION=v2.3.7
    command: /home/run.sh
  nginx:
    container_name: medcattrainer_nginx
    image: cogstacksystems/medcat-trainer-nginx:latest
    restart: always
    volumes:
      - api-media:/home/api/media
      - api-static:/home/api/static
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    depends_on:
      - medcattrainer
  solr:
    container_name: mct_solr
    image: solr:8
    restart: always
    expose:
      - "8983"
    volumes:
      - solr-data:/var/solr
    command:
      - -cloud  # solr cloud launches
volumes:
  api-media:
  api-static:
  api-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/data
  solr-data:
